apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: spring-app
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: server:1.2.0
          imagePullPolicy: Never
          resources:
            requests:
              memory: "512Mi"
              cpu: "5m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
