apiVersion: v1
kind: ConfigMap
metadata:
  name: book-service
  namespace: spring-app
data:
  application.yaml: |-
    otel:
      exporter:
        otlp:
          traces:
            endpoint: "http://otel-agent-collector.spring-app.svc.cluster.local:4318/v1/traces"
          logs:
            endpoint: "http://otel-agent-collector.spring-app.svc.cluster.local:4318/v1/logs"
          metrics:
            endpoint: "http://otel-agent-collector.spring-app.svc.cluster.local:4318/v1/metrics"
    logging:
      level:
        com.stefanovich.bookservice.api.BookApi: debug
    spring:
      datasource:
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        url: jdbc:postgresql://localhost:5433/book
      jpa:
        hibernate:
          ddl-auto: update