scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
#      - targets: ["collector:8889"]
#      - targets: ["host.docker.internal:8080"]
      - targets: ["otel-collector.kuber.com"]