kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: spring-app
  name: spring-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps","pods"]
    verbs: ["get","list"]